[build]
  command = "npm run build"
  publish = "_site"
  functions = "_site/api"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
